#cloud-config

autoinstall:
  version: 1
  interactive-sections:
    - identity
  locale: en_US.UTF-8
  keyboard:
    layout: "br"
    variant: ""
    toggle: null
  timezone: "America/Sao_Paulo"
  storage:
    layout:
      name: lvm
      match:
        size: largest
      preserve: false

  late-commands:
    - echo "==============Comecei os comandos============"
    - mkdir -p /mnt/pendrive
    - mount /dev/sdb1 /mnt/pendrive
    - cp /mnt/pendrive/posinstall3.sh /target/root/posinstall3.sh
    - chmod +x /target/root/posinstall3.sh    
    - curtin in-target -- /root/posinstall3.sh
    - echo "============Terminei os comandos============"
  shutdown: reboot    
