#cloud-config

autoinstall:
  version: 1
  interactive-sections:
    - network
  
  identity: 
    hostname: administrator
    username: kiosk
    password: "$6$P4EWCxO5uckDy.Do$qCdcAoqC1EsFRVKZKVhbhzPP8Vg7YaempLDemNJD8hR4ucu3Q5tLgW5QtZ2auCIXIfTalJ8eDs2xiT1tzJMpX1"
  locale: en_US.UTF-8
  keyboard:
    layout: br
  timezone: "America/Sao_Paulo"
  storage:
    layout:
      name: lvm
      match:
        size: largest
      preserve: false

  late-comands:
    - curtin in-target -- /bin/bash /home/ubuntu/Desktop/posinstall3.sh
    
  shutdown: reboot    
