#cloud-config

autoinstall:
  version: 1
  interactive-sections:
    - identity
  locale: en_US.UTF-8
  keyboard:
    layout: br
    variant: abnt2
  timezone: "America/Sao_Paulo"
  storage:
    layout:
      name: lvm
      match:
        size: largest
      preserve: false

  late-commands:
    - echo "_______Comecei os comandos_______"

    - curtin in-target -- lsblk
    - curtin in-target -- mount
    - curtin in-target -- ls -la /media/
    - curtin in-target -- ls -la /media/administrator
    - curtin in-target -- ls -la /media/administrator/POSINSTALL
    - curtin in-target -- /bin/bash /root/posinstall3.sh


    - echo "_______Terminei os comandos_______"
  shutdown: reboot    
