#cloud-config

autoinstall:
  version: 1
  interactive-sections:
    - storage
  identity: 
    hostname: administrator
    username: administrator
    password: "$6$P4EWCxO5uckDy.Do$qCdcAoqC1EsFRVKZKVhbhzPP8Vg7YaempLDemNJD8hR4ucu3Q5tLgW5QtZ2auCIXIfTalJ8eDs2xiT1tzJMpX1"
  locale: en_US.UTF-8
  keyboard:
    layout: br
  timezone: "America/Sao_Paulo"
  storage:
    layout:
      name: lvm
      match:
        size: largest
      preserve: false

  late-comands:
    - curtin in-target -- apt-get update
    - curtin in-target -- apt install git -y
    - curtin in-target -- git clone https://github.com/GabrielRios763/UbuntuTests.git

  shutdown: reboot    
